<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SoftwareModel" nsURI="http:///SoftwareModel.ecore" nsPrefix="SoftwareModel">
  <eSubpackages name="DomainEntities" nsURI="http:///SoftwareModel/DomainEntities.ecore"
      nsPrefix="SoftwareModel.DomainEntities">
    <eClassifiers xsi:type="ecore:EClass" name="RoomType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="view" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="disableAccess" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rate" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="smoking" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="petsAllowed" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="roomTypeId" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bedtype" ordered="false"
          lowerBound="1" upperBound="-1" eType="#//DomainEntities/BedType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="BedType">
      <eLiterals name="King"/>
      <eLiterals name="Queen" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PaymentDetails">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="phoneNumber" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Reservation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="roombooking" ordered="false"
          lowerBound="1" upperBound="-1" eType="#//DomainEntities/RoomBooking"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="preliminaryCheckIn" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="preliminaryCheckOut"
          ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="reservationId" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="discountCode" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="paymentdetails" ordered="false"
          lowerBound="1" eType="#//DomainEntities/PaymentDetails"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RoomBooking">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="IsCheckedIn" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="roomresponsible" ordered="false"
          lowerBound="1" eType="#//DomainEntities/RoomResponsible"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="adults" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="children" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkOutDate" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkInDate" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="roomtype" ordered="false"
          lowerBound="1" eType="#//DomainEntities/RoomType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RoomResponsible">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="phoneNumber" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Bill"/>
    <eClassifiers xsi:type="ecore:EClass" name="Room">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="availability" ordered="false"
          lowerBound="1" eType="#//DomainEntities/Availability"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Availability">
      <eLiterals name="Availible"/>
      <eLiterals name="Used" value="1"/>
      <eLiterals name="UnderMaintenence" value="2"/>
      <eLiterals name="ToBeCleaned" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Service">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceDate" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="DataAccess" nsURI="http:///SoftwareModel/DataAccess.ecore" nsPrefix="SoftwareModel.DataAccess">
    <eClassifiers xsi:type="ecore:EClass" name="ReservationsRepository">
      <eOperations name="update" ordered="false" lowerBound="1">
        <eParameters name="reservation" ordered="false" lowerBound="1" eType="#//DomainEntities/Reservation"/>
      </eOperations>
      <eOperations name="get" ordered="false" lowerBound="1" eType="#//DomainEntities/Reservation">
        <eParameters name="reservationNumber" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="addNew" ordered="false" lowerBound="1" eType="#//DomainEntities/Reservation">
        <eParameters name="reservation" ordered="false" lowerBound="1" eType="#//DomainEntities/Reservation"/>
      </eOperations>
      <eOperations name="remove" ordered="false" lowerBound="1">
        <eParameters name="reservationNumber" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="databasecontext" ordered="false"
          lowerBound="1" eType="#//DataAccess/DatabaseContext"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DatabaseContext">
      <eStructuralFeatures xsi:type="ecore:EReference" name="rooms" ordered="false"
          upperBound="-1" eType="#//DomainEntities/Room"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="roomTypes" ordered="false"
          upperBound="-1" eType="#//DomainEntities/RoomType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="reservations" ordered="false"
          upperBound="-1" eType="#//DomainEntities/Reservation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="roomBookings" ordered="false"
          upperBound="-1" eType="#//DomainEntities/RoomBooking"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RoomBookingsRepository">
      <eOperations name="update" ordered="false" lowerBound="1">
        <eParameters name="roomBooking" ordered="false" lowerBound="1" eType="#//DomainEntities/RoomBooking"/>
      </eOperations>
      <eOperations name="get" ordered="false" lowerBound="1">
        <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      </eOperations>
      <eOperations name="get" ordered="false" lowerBound="1">
        <eParameters name="reservationNumber" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="databasecontext" ordered="false"
          lowerBound="1" eType="#//DataAccess/DatabaseContext"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AuthorizationRepository">
      <eOperations name="getPasswords" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="databasecontext" ordered="false"
          lowerBound="1" eType="#//DataAccess/DatabaseContext"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RoomRepository">
      <eOperations name="updateRoom" ordered="false" lowerBound="1">
        <eParameters name="room" ordered="false" lowerBound="1" eType="#//DomainEntities/Room"/>
      </eOperations>
      <eOperations name="updateRoomType" ordered="false" lowerBound="1">
        <eParameters name="roomType" ordered="false" lowerBound="1" eType="#//DomainEntities/RoomType"/>
      </eOperations>
      <eOperations name="getRoom" ordered="false" lowerBound="1">
        <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="getRoomType" ordered="false" lowerBound="1">
        <eParameters name="roomTypeId" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="removeRoom" ordered="false" lowerBound="1">
        <eParameters name="room" ordered="false" lowerBound="1" eType="#//DomainEntities/Room"/>
      </eOperations>
      <eOperations name="addRoom" ordered="false" lowerBound="1">
        <eParameters name="room" ordered="false" lowerBound="1" eType="#//DomainEntities/Room"/>
      </eOperations>
      <eOperations name="getRooms" ordered="false" upperBound="-1" eType="#//DomainEntities/Room"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="databasecontext" ordered="false"
          lowerBound="1" eType="#//DataAccess/DatabaseContext"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="BusinessLogic" nsURI="http:///SoftwareModel/BusinessLogic.ecore"
      nsPrefix="SoftwareModel.BusinessLogic">
    <eClassifiers xsi:type="ecore:EClass" name="Reservations">
      <eOperations name="updateReservationDetails" ordered="false" lowerBound="1">
        <eParameters name="reservation" ordered="false" lowerBound="1" eType="#//DomainEntities/Reservation"/>
      </eOperations>
      <eOperations name="make" ordered="false" lowerBound="1" eType="#//DomainEntities/Reservation">
        <eParameters name="selectedRooms" ordered="false" lowerBound="1" upperBound="-1"
            eType="#//DomainEntities/RoomBooking"/>
        <eParameters name="paymentDetails" ordered="false" lowerBound="1" eType="#//DomainEntities/PaymentDetails"/>
        <eParameters name="payNow" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eOperations>
      <eOperations name="cancel" ordered="false" lowerBound="1">
        <eParameters name="reservation" ordered="false" lowerBound="1" eType="#//DomainEntities/Reservation"/>
      </eOperations>
      <eOperations name="getReservation" ordered="false" lowerBound="1" eType="#//DomainEntities/Reservation">
        <eParameters name="reservationNumber" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="reservationsrepository"
          ordered="false" lowerBound="1" eType="#//DataAccess/ReservationsRepository"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RoomBookings">
      <eOperations name="checkOut" ordered="false" lowerBound="1">
        <eParameters name="roomBooking" ordered="false" lowerBound="1" eType="#//DomainEntities/RoomBooking"/>
      </eOperations>
      <eOperations name="checkIn" ordered="false" lowerBound="1">
        <eParameters name="roomBooking" ordered="false" lowerBound="1" eType="#//DomainEntities/RoomBooking"/>
      </eOperations>
      <eOperations name="findByRoomNr" ordered="false" lowerBound="1">
        <eParameters name="roomNr" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="roombookingsrepository"
          ordered="false" lowerBound="1" eType="#//DataAccess/RoomBookingsRepository"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="availibleroomfinder"
          ordered="false" lowerBound="1" eType="#//BusinessLogic/AvailibleRoomFinder"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AvailibleRoomFinder">
      <eOperations name="availableRoomTypes" ordered="false" upperBound="-1" eType="#//DomainEntities/RoomType">
        <eParameters name="adults" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="children" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="startDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
        <eParameters name="endDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      </eOperations>
      <eOperations name="availibleRoom" ordered="false" upperBound="-1" eType="#//DomainEntities/RoomType">
        <eParameters name="roomBooking" ordered="false" lowerBound="1" eType="#//DomainEntities/RoomBooking"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="roomrepository" ordered="false"
          lowerBound="1" eType="#//DataAccess/RoomRepository" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="roombookingsrepository"
          ordered="false" lowerBound="1" eType="#//DataAccess/RoomBookingsRepository"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RoomOperations">
      <eOperations name="modifyRate" ordered="false" lowerBound="1">
        <eParameters name="roomTypeId" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="rate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      </eOperations>
      <eOperations name="makeRoomAvailable" ordered="false" lowerBound="1">
        <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="addRoom" ordered="false" lowerBound="1">
        <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="availability" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEnumerator"/>
      </eOperations>
      <eOperations name="removeRoom" ordered="false" lowerBound="1">
        <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="makeRoomUnavailable" ordered="false" lowerBound="1">
        <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="roomrepository" ordered="false"
          lowerBound="1" eType="#//DataAccess/RoomRepository" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Authorizer">
      <eOperations name="Authorize" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean">
        <eParameters name="password" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="managerrepository" ordered="false"
          lowerBound="1" eType="#//DataAccess/AuthorizationRepository" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Rooms">
      <eOperations name="checkOut" ordered="false" lowerBound="1">
        <eParameters name="roomBooking" ordered="false" lowerBound="1" eType="#//DomainEntities/RoomBooking"/>
      </eOperations>
      <eOperations name="checkIn" ordered="false" lowerBound="1">
        <eParameters name="roomBooking" ordered="false" lowerBound="1" eType="#//DomainEntities/RoomBooking"/>
      </eOperations>
      <eOperations name="getBooking" ordered="false" lowerBound="1" eType="#//DomainEntities/RoomBooking">
        <eParameters name="roomNr" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      </eOperations>
      <eOperations name="availibleRoomTypes" ordered="false" upperBound="-1" eType="#//DomainEntities/RoomType">
        <eParameters name="adults" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
        <eParameters name="children" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
        <eParameters name="startDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
        <eParameters name="endDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      </eOperations>
      <eOperations name="getBooking" ordered="false" lowerBound="1" eType="#//DomainEntities/RoomBooking">
        <eParameters name="nameOfRoomResponsible" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Presentation" nsURI="http:///SoftwareModel/Presentation.ecore"
      nsPrefix="SoftwareModel.Presentation">
    <eClassifiers xsi:type="ecore:EClass" name="CustomerHomeView" eSuperTypes="#//Presentation/IView"/>
    <eClassifiers xsi:type="ecore:EClass" name="IView" abstract="true" interface="true">
      <eOperations name="Run" ordered="false" lowerBound="1">
        <eParameters name="frame" ordered="false" lowerBound="1" eType="#//Presentation/Frame"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Frame">
      <eOperations name="ChangeView" ordered="false" lowerBound="1">
        <eParameters name="view" ordered="false" lowerBound="1" eType="#//Presentation/IView"/>
      </eOperations>
      <eOperations name="Start" ordered="false" lowerBound="1">
        <eParameters name="View" ordered="false" lowerBound="1" eType="#//Presentation/IView"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="currentView" ordered="false"
          lowerBound="1" eType="#//Presentation/IView"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RoomBookingView" eSuperTypes="#//Presentation/IView">
      <eStructuralFeatures xsi:type="ecore:EReference" name="rooms" ordered="false"
          lowerBound="1" eType="#//BusinessLogic/Rooms" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReservationView" eSuperTypes="#//Presentation/IView">
      <eStructuralFeatures xsi:type="ecore:EReference" name="reservations" ordered="false"
          lowerBound="1" eType="#//BusinessLogic/Reservations" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RoomManagementView" eSuperTypes="#//Presentation/IView">
      <eStructuralFeatures xsi:type="ecore:EReference" name="roomoperations" ordered="false"
          lowerBound="1" eType="#//BusinessLogic/RoomOperations" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LoginView" eSuperTypes="#//Presentation/IView">
      <eStructuralFeatures xsi:type="ecore:EReference" name="authorizer" ordered="false"
          lowerBound="1" eType="#//BusinessLogic/Authorizer" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EmployeeHomeView" eSuperTypes="#//Presentation/IView"/>
    <eClassifiers xsi:type="ecore:EClass" name="MakeReservationView" eSuperTypes="#//Presentation/IView">
      <eStructuralFeatures xsi:type="ecore:EReference" name="reservations" ordered="false"
          lowerBound="1" eType="#//BusinessLogic/Reservations" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rooms" ordered="false"
          lowerBound="1" eType="#//BusinessLogic/Rooms"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="ClassDiagramEdges" nsURI="http:///SoftwareModel/ClassDiagramEdges.ecore"
      nsPrefix="SoftwareModel.ClassDiagramEdges"/>
</ecore:EPackage>
