/**
 */
package SoftwareModel.BusinessLogic.provider;

import SoftwareModel.BusinessLogic.util.BusinessLogicAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class BusinessLogicItemProviderAdapterFactory extends BusinessLogicAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public BusinessLogicItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link SoftwareModel.BusinessLogic.Reservations} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReservationsItemProvider reservationsItemProvider;

	/**
	 * This creates an adapter for a {@link SoftwareModel.BusinessLogic.Reservations}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReservationsAdapter() {
		if (reservationsItemProvider == null) {
			reservationsItemProvider = new ReservationsItemProvider(this);
		}

		return reservationsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link SoftwareModel.BusinessLogic.RoomBookings} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoomBookingsItemProvider roomBookingsItemProvider;

	/**
	 * This creates an adapter for a {@link SoftwareModel.BusinessLogic.RoomBookings}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRoomBookingsAdapter() {
		if (roomBookingsItemProvider == null) {
			roomBookingsItemProvider = new RoomBookingsItemProvider(this);
		}

		return roomBookingsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link SoftwareModel.BusinessLogic.AvailibleRoomFinder} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AvailibleRoomFinderItemProvider availibleRoomFinderItemProvider;

	/**
	 * This creates an adapter for a {@link SoftwareModel.BusinessLogic.AvailibleRoomFinder}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAvailibleRoomFinderAdapter() {
		if (availibleRoomFinderItemProvider == null) {
			availibleRoomFinderItemProvider = new AvailibleRoomFinderItemProvider(this);
		}

		return availibleRoomFinderItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link SoftwareModel.BusinessLogic.RoomOperations} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoomOperationsItemProvider roomOperationsItemProvider;

	/**
	 * This creates an adapter for a {@link SoftwareModel.BusinessLogic.RoomOperations}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRoomOperationsAdapter() {
		if (roomOperationsItemProvider == null) {
			roomOperationsItemProvider = new RoomOperationsItemProvider(this);
		}

		return roomOperationsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link SoftwareModel.BusinessLogic.Authorizer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AuthorizerItemProvider authorizerItemProvider;

	/**
	 * This creates an adapter for a {@link SoftwareModel.BusinessLogic.Authorizer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAuthorizerAdapter() {
		if (authorizerItemProvider == null) {
			authorizerItemProvider = new AuthorizerItemProvider(this);
		}

		return authorizerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link SoftwareModel.BusinessLogic.Rooms} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoomsItemProvider roomsItemProvider;

	/**
	 * This creates an adapter for a {@link SoftwareModel.BusinessLogic.Rooms}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRoomsAdapter() {
		if (roomsItemProvider == null) {
			roomsItemProvider = new RoomsItemProvider(this);
		}

		return roomsItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (reservationsItemProvider != null) reservationsItemProvider.dispose();
		if (roomBookingsItemProvider != null) roomBookingsItemProvider.dispose();
		if (availibleRoomFinderItemProvider != null) availibleRoomFinderItemProvider.dispose();
		if (roomOperationsItemProvider != null) roomOperationsItemProvider.dispose();
		if (authorizerItemProvider != null) authorizerItemProvider.dispose();
		if (roomsItemProvider != null) roomsItemProvider.dispose();
	}

}
